backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets

collections:
  - name: solutions
    label: Software Solution
    folder: src/markdown/products
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string, required: false }
      - { name: mini_description, label: Thumbnail Description, widget: string, required: true }
      - { name: github_link, label: Github Link, widget: string, required: false }
      - { name: heroku_link, label: Heroku Link, widget: string, required: false}
      - { name: youtube_link, label: Youtube Embed Link, widget: string, required: false}
      - label: "Features"
        name: "features"
        widget: "list"
        allow_add: true
        default: ["NONE"]
        summary: '{{fields.feature}}'
        fields: 
          - {label: Feature, name: feature, widget: string}
      - { name: body, label: Body (Full Description), widget: markdown, required: true}

  - name: research
    label: Research
    folder: src/markdown/research
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string, required: false }
      - { name: mini_description, label: Thumbnail Description, widget: string, required: true }
